[mysql]
host="111.118.215.51"
port=3306
user="joillhqw_attendance2022"
password="nihita1981"
database="joillhqw_attendance2022"


[passwords]
kddlakshmi = "lakshmi@2022"
admin = "admin@biet@2022"
dsrikar = "srikar@2022"
gsushma = "sushma@2022"